---
- name: Setup local workstation
  hosts: localhost
  vars:
    install_homebrwe_if_missing: false
  vars_files:
    - ./vars/custom.yml
  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing
  tasks:
    - name: Get the username running the deploy | whoami
      local_action: command whoami
      register: whoami_output
      check_mode: no

    - name: Check current shell
      shell: echo $SHELL
      register: current_shell_output
      check_mode: no

    - debug:
        var: current_shell_output

    - name: zsh | Installs zsh | brew
      community.general.homebrew:
        name: zsh
      when: current_shell_output.stdout != "/bin/zsh"

    - name: zsh | Sets zsh as default shell for root | command
      command: chsh -s /bin/zsh
      register: zsh_for_root
      failed_when: zsh_for_root.rc >= 1
      changed_when: zsh_for_root.rc == 0
      when: current_shell_output.stdout != "/bin/zsh"

    - name: zsh | Sets zsh as default shell for {{ whoami_output.stdout }} | command
      command: chsh -s /bin/zsh {{ whoami_output.stdout }}
      register: zsh_for_user
      failed_when: zsh_for_user.rc >= 1
      changed_when: zsh_for_user.rc == 0
      when: current_shell_output.stdout != "/bin/zsh"

    - name: alacritty | Installs alacritty | brew cask
      community.general.homebrew_cask:
        name: alacritty

    - name: neovim | Installs neovim | brew
      community.general.homebrew:
        name: neovim

    - name: tmux | Installs tmux | brew
      community.general.homebrew:
        name: tmux

    - name: d12frosted/emacs-plus | Tap for emacs-plus | brew tap
      community.general.homebrew_tap:
        name: d12frosted/emacs-plus

    - name: emacs-plus | Installs emacs-plus | brew
      community.general.homebrew:
        name: emacs-plus
        options: with-no-titlebar

    - name: emacs-plus | Create symlink | file
      ansible.builtin.file:
        src: /usr/local/opt/emacs-plus@27/Emacs.app
        dest: /Applications/Emacs.app
        state: link

    - name: ripgrep | Installs ripgrep | brew
      community.general.homebrew:
        name: ripgrep

    - name: tig | Installs tig | brew
      community.general.homebrew:
        name: tig

    - name: cmake | Installs cmake | brew
      community.general.homebrew:
        name: cmake

    - name: go | Installs go | brew
      community.general.homebrew:
        name: go

    - name: python | Installs python | brew
      community.general.homebrew:
        name: python

    - name: pyenv | Installs pyenv | brew
      community.general.homebrew:
        name: pyenv

    - name: pyenv-virtualenv | Installs pyenv-virtualenv | brew
      community.general.homebrew:
        name: pyenv-virtualenv

    - name: python | Installs neovim package | pip
      pip:
        name: neovim
        executable: ~/.pyenv/shims/pip3

    - name: rbenv | Installs rbenv | brew
      community.general.homebrew:
        name: rbenv

    - name: nvm | Installs nvm | brew
      community.general.homebrew:
        name: nvm

    - name: AdoptOpenJDK8 | Tap AdoptOpenJDK | brew tap
      community.general.homebrew_tap:
        name: AdoptOpenJDK/openjdk

    - name: AdoptOpenJDK8 | Installs AdoptOpenJDK8 | brew cask
      community.general.homebrew_cask:
        name: adoptopenjdk8

    - name: fzf | Installs fzf | brew
      community.general.homebrew:
        name: fzf

    - name: fzf | Installs bat | brew
      community.general.homebrew:
        name: bat

    - name: karabiner-elements | Installs karabiner-elements | brew cask
      community.general.homebrew_cask:
        name: karabiner-elements

    - name: yabai | Tap koekeishiya/formulae | brew tap
      community.general.homebrew_tap:
        name: koekeishiya/formulae

    - name: yabai | Installs yabai | brew
      community.general.homebrew:
        name: yabai

    - name: skhd | Installs skhd | brew
      community.general.homebrew:
        name: skhd

    - name: jq | Installs jq | brew
      community.general.homebrew:
        name: jq

    - name: limelight | Clone limelight repo | git
      ansible.builtin.git:
        repo: https://github.com/koekeishiya/limelight.git
        dest: ~/tmp/limelight-temp

    - name: limelight | Build limelight | make
      community.general.make:
        chdir: ~/tmp/limelight-temp
      when: not ansible_check_mode

    - name: limelight | Copy binary | file
      ansible.builtin.copy:
        src: ~/tmp/limelight-temp/bin/limelight
        dest: /usr/local/bin/limelight
        mode: '755'
      when: not ansible_check_mode

    - name: limelight | Remove repo | file
      ansible.builtin.file:
        path: ~/tmp/limelight-temp
        state: absent

    - name: hammerspoon | Install hammerspoon | brew cask
      community.general.homebrew_cask:
        name: hammerspoon

    - name: rcm | Installs rcm | brew
      community.general.homebrew:
        name: rcm

    - name: rcm | Installs rcm config
      command:
        cmd: rcup rcrc
      register: rcup_rcrc_output
      failed_when: rcup_rcrc_output.rc >= 1
      changed_when: rcup_rcrc_output.rc == 0

    - name: rcm | Installs dotfiles
      command:
        cmd: rcup
      register: rcup_output
      failed_when: rcup_output.rc >= 1
      changed_when: rcup_output.rc == 0
