---
editors_emacs_formula: emacs-plus@31
editors_emacs_install_options:
  - with-modern-purple-flat-icon
editors_emacs_app_destination: /Applications/Emacs.app
editors_emacs_app_source: "{{ homebrew_prefix }}/opt/{{ editors_emacs_formula }}/Emacs.app"
