---
dotfiles_repo_root: "{{ playbook_dir | dirname }}"
dotfiles_private_vars_file: "{{ dotfiles_repo_root }}/vars/custom.yml"
install_homebrew_if_missing: false
homebrew_prefix: "{{ '/opt/homebrew' if ansible_facts['architecture'] == 'arm64' else '/usr/local' }}"
