---
editors_homebrew_taps:
  - d12frosted/emacs-plus
editors_homebrew_formulae:
  - neovim
  - tmux
editors_homebrew_casks:
  - alacritty
editors_emacs_formula: emacs-plus@30
editors_emacs_install_options:
  - with-modern-purple-flat-icon
editors_emacs_app_destination: /Applications/Emacs.app
editors_emacs_app_source_arm64: "/opt/homebrew/opt/{{ editors_emacs_formula }}/Emacs.app"
editors_emacs_app_source_x86_64: "/usr/local/opt/{{ editors_emacs_formula }}/Emacs.app"
editors_vim_plug_url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
editors_vim_plug_path: "{{ lookup('env', 'XDG_DATA_HOME') | default(ansible_env.HOME + '/.local/share', true) }}/nvim/site/autoload/plug.vim"
