---
- name: node | darwin entrypoint
  ansible.builtin.import_tasks: darwin.yml
  when: ansible_facts['os_family'] == 'Darwin'

- name: node | unsupported platform placeholder
  ansible.builtin.debug:
    msg: "Node role currently supports Darwin only."
  when: ansible_facts['os_family'] != 'Darwin'
