---
- name: cli_tools | darwin | import platform tasks
  ansible.builtin.import_tasks: darwin.yml
  when: ansible_facts['os_family'] == 'Darwin'

- name: cli_tools | unsupported platform placeholder
  ansible.builtin.debug:
    msg: "cli_tools role currently supports Darwin only."
  when: ansible_facts['os_family'] != 'Darwin'
